### ISSUE TITLE
Getting data from Dispatch

### ISSUE THREAD

**Issue by eftanzer** [DispatchMe/v3-api-docs#10]
**GET vs. webhooks:** In reading this document, I might expect that the way I consume information from Dispatch is via GET calls. The top section articulates `Our REST API allows you to easily interact with our core business entities to implement your workflow in our platform.` We should include a description or section on how to consume data from Dispatch with options:
- Periodic CSVs
- [Webhooks](https://paper.dropbox.com/doc/Carrier-Webhooks-mlEOovWs3UtF7ZriFsBg6)

**Comment by jraede** [comment]
Thanks @eftanzer. We are separately working on webhooks which we'll include in this documentation. The goal of this is just to document what we currently support and then add to it as we add more standardized features, so we will be adding documentation for self-service webhooks once they are implemented.

**Comment by jraede** [comment]
I will add a header explaining that we offer webhooks and to speak to your account manager.
