### ISSUE TITLE
Delete rights on objects

### ISSUE THREAD

**Issue by eftanzer** [DispatchMe/v3-api-docs#4]
Do we want to give `Delete` access through our public API on any objects? Or do we want to restrict this? I vote to restrict because of the potential impact down the line. Some our of partners may choose to delete and appointment instead of canceling an appointment, which could be unexpected for the org or customer. Or worse, they might delete more substantial records.

**Comment by jraede** [comment]
All of our deletes are *soft*, so data issues are limited to "that's not there anymore" and not "this doesn't work anymore". With a public API we can't control how people use the system, but if we find that people are deleting appointments when they should be canceling we can add a disclaimer and amend the documentation.
